### PR TITLE
Fix Duplicated Template Parameter in EN Localisation

### LINKED ISSUE #8: Duplicated Template Parameters in EN/ES/FR Locale
The string on line 274 (`"{0} jumps on to {0} and squishes them."`) in the English, Spanish, and French localisation duplicates the template parameter. PR #7 addresses this error for the English localisation but not the French or Spanish translations.

Note that the Swedish translation is unaffected, either because they were fixed or the parameters were copied incorrectly during translation.

I know of this one instance of template parameter duplication. There may be more but I haven’t checked.

### PR DESCRIPTION
**Pull request by lesslih**
## Type

- [x] Edit
- [x] English Edit
- [ ] Full Audit
- [ ] Incomplete Audit
- [ ] Update Outdated Translation(s)
- [ ] Enhance Translation(s)

## Information

The string `"{0} jumps on to {0} and squishes them."` on line 274 duplicates the `{0}` template parameter, rendering the name of the command caller twice. This corrects the second parameter to be `1` (the target user).

This PR fixes the error in the English localisation, but it exists in all translations except for Swedish (it was either fixed or the template parameters weren’t copied “correctly”). ~~However, I’m not confident enough to touch the French and Spanish translations and therefore I’ve opted to leave those as-is, deferring it to those who actually speak the respective languages (issue #8)~~.

(This PR now closes #8.)

### CODE REVIEW

**Review by MrGriefs — CHANGES_REQUESTED** [review]
Please go ahead and fix this issue on other locales - PRs that introduce partially completed commits cannot be added to the commit history.  
This is an unknown bug and has probably been overlooked by other translators.

**Comment by lesslih** [comment]
> Please go ahead and fix this issue on other locales - PRs that introduce partially completed commits cannot be added to the commit history. This is an unknown bug and has probably been overlooked by other translators.

Acknowledged.

**Comment by MrGriefs** [comment]
Let me know when you're ready to merge.

**Review by MrGriefs — APPROVED** [review]

**Comment by lesslih** [comment]
Ready to merge

**Comment by lesslih** [comment]
Ready to merge

**Pull request merged**
